### ISSUE TITLE
Suggestion - WorldGuard support to block flight in specific regions rather than whole world only.

### ISSUE THREAD

**Issue by mibby** [PyvesB/AntiWorldFly#12]

**Comment by mibby** [comment]
Bumping request so AntiWorldFly could have feature parity with NoFlyZone as a suitable updated replacement.

https://www.spigotmc.org/resources/noflyzone.3321/

**Comment by Sidpatchy** [comment]
I've started work on this, I'll probably finish within the next week or so.

**Comment by Sidpatchy** [comment]
Feature released in v2.5.0, closing issue.

**Comment by mibby** [comment]
Is it possible for the WorldGuard flags to take priority over bypass permissions if you allow players to bypass specific worlds but want to have an area where they cannot?
