### ISSUE TITLE
Color in title not working

### ISSUE THREAD

**Issue by SeruhioX** [PyvesB/AntiWorldFly#16]
fly-disabled-title

As the title says, I tried to put the title in color in the following way "&9AntiWorldFly" and it does not appear in color, you see the message "&9AntiWorldFly"

**Comment by PyvesB** [comment]
Hello @SeDark,

Have you tried removing the spurious space (`&9AntiWorldFly`)?

Cheers,

Pyves

**Comment by SeruhioX** [comment]
Yes, I was wrong to do the problem, it doesn't work.

**Comment by PyvesB** [comment]
This seems to be a change in behaviour in how Spigot handles colours in recent versions of Minecraft. For now, simply try using `§9AntiWorldFly` instead. 😉
