### ISSUE TITLE
CMI not working

### ISSUE THREAD

**Issue by Polypodiozoa** [PyvesB/AntiWorldFly#19]
Hi, your plugin doesnt work with CMI, could you fix that?

**Comment by PyvesB** [comment]
Hi, what is CMI and what exactly doesn't work?

**Comment by Italoplcl** [comment]
I use cmi and it works perfect

**Comment by PyvesB** [comment]
Thanks for the feedback @Italoplcl . I'll simply close this issue given the absence of news. 😉
