### ISSUE TITLE
AWF (class com.hm.antiworldfly.listener.ToggleGlide)

### ISSUE THREAD

**Issue by uFireza** [PyvesB/AntiWorldFly#21]
Plugin Version: 2.4.0

Minecraft Version: 1.8.8

Bro I just get an error like this every time I turn on the server: [Server thread/ERROR]: [AntiWorldFly] Plugin AntiWorldFly v2.4.0 has failed to register events for class com.hm.antiworldfly.listener.ToggleGlide because org/bukkit/event/entity/EntityToggleGlideEvent does not exist.

**Comment by Sidpatchy** [comment]
I know exactly what's causing this. I just forgot to fix it before releasing this version. Should be a non-fatal error, just a nuisance in the console.

It's failing to activate the class on servers lower than version 1.9 since the EntityToggleGlideEvent didn't exist before 1.9.
