### ISSUE TITLE
BUG With Boats

### ISSUE THREAD

**Issue by Maximas14** [PyvesB/AntiWorldFly#22]
When i'm in the corner of a boat at the floor, the servers kicks me for "fly". Even when i'm at /login the server kicks me out

Plugin Version: last one

Minecraft Version: 1.16.5

## Expected Behavior
i don't know

## Current Behavior
The server kicks for flying
## Steps to Reproduce
1. Boat almost falling
2. step on the corner
3. get kicked

## Context (Environment)
i just want to know if this is serious
An image: [https://imgur.com/q9BRgDe](url)

**Comment by Sidpatchy** [comment]
This is a bug with Spigot/Vanilla servers' flight preventions. You can test this by attempting to reproduce this on a server without AWF installed.

AntiWorldFly never has and never will function as an anti-cheat. It has never kicked players for flight. AntiWorldFly only serves to prevent "vanilla" flight in specified worlds, it does not attempt to detect flight "hacks".

On my servers I have fixed this by setting `allow-flight` to true in the `server.properties` file.
