### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Justsean2** [PyvesB/AntiWorldFly#23]
Hello! I wanna make it so my staff are able to fly in PVP however players aren't able to. Is there any way to do so with Anti World Fly?

**Comment by Sidpatchy** [comment]
You haven't really given enough details for a proper answer but assuming PvP is a separate world and you only want your staff to be able to fly in that world, you could give the permission `antiworldfly.fly.<world>` to your staff.

[More documentation on the plugin's perms](https://github.com/PyvesB/AntiWorldFly/wiki/Permissions)

**Comment by Sidpatchy** [comment]
Given there has been no further clarification or activity, I'm gonna go ahead and close this. If you still need help, feel free to reopen.
