### ISSUE TITLE
German language file

### ISSUE THREAD

**Issue by ghost** [PyvesB/AntiWorldFly#25]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I am a native speaker and living in Germany. That's why I created a language file.

**Additional context**
yml is in the zip file. Maybe you want to add it to your repository.
[lang-DE.zip](https://github.com/PyvesB/AntiWorldFly/files/7025731/lang-DE.zip)

**Comment by Sidpatchy** [comment]
Thanks for your work! I'd be happy to add it to AntiWorldFly, would you like to create a pull request with the new lang file so you get credit for it on GitHub?

**Comment by PyvesB** [comment]
You could also set the commit's author to their no-reply GitHub mail address, they will get credit without having to submit a pull request. 😉
