### ISSUE TITLE
A way to also disable Elytras

### ISSUE THREAD

**Issue by ReZuni** [PyvesB/AntiWorldFly#27]
Basically, there is no updated Anti Elytra Plugins and this would fit into the Plugin since its also is some kind of Fly

**Comment by Sidpatchy** [comment]
Apologies for the time it took me to reply. AntiWorldFly already supports disabling elytras as of v2.4.

Elytra blocking can be enabled in the config by toggling the option `elytraDisabled`, more info may be found on the config option [on the wiki](https://github.com/PyvesB/AntiWorldFly/wiki/Configuration#elytradisabled)

Additionally, you are able to further control elytra blocking with permissions, which may also be found [on the wiki](https://github.com/PyvesB/AntiWorldFly/wiki/Permissions)
