### ISSUE TITLE
Fly auto enable 

### ISSUE THREAD

**Issue by karib5** [PyvesB/AntiWorldFly#30]
last night i updated Anti World Fly v2.5.0 now every time players go to end and come back to overworld there flight auto turn on.
our nether and end world fly is disabled but our servers vip can fly but players whose vip already expire they can also fly when they transfer end to overworld

**Comment by karib5** [comment]
![image_2021-12-18_115639](https://user-images.githubusercontent.com/65844386/146631074-0158d532-2cb7-475c-bc55-cb7ac42c4145.png)
this is the message which everyone getting. even though they dont have any permission for fly

**Comment by Sidpatchy** [comment]
Please, at a bare minimum, provide the following to assist me in reproducing this issue:
```
Plugin Version:

Minecraft Version:

Spigot/CraftBukkit version: <!-- Run /version and paste the output here -->

Other Plugins you are using: <!-- ex. screenshot of /plugins -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.
```

Additionally, is anything logged in the console when this happens?

I've said it before, and I'll say it again: The issue templates exist for a reason, please use them (instead of deleting them) in the future.

**Comment by karib5** [comment]
Plugin Version: v2.5.0

Minecraft Version: 1.17.1

This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)

plugins: 
ActionHealth, AdvancedBan, ajParkour, AltDetector, AntiWorldFly, AuthMe, BanAnnouncer*, BuycraftX, ChatReaction, ClearLag, CoreProtect, DiscordSRV, dynmap, EntityDetection, EpicGuard*, EpicHeads, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FarmControl, FastLogin, GriefPrevention, GriefPreventionFlags, GSit, Harbor, Holograms, InteractiveChat, InventoryRollbackPlus, LitePlaytimeRewards, LuckPerms, Minepacks, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MyCommand, PlaceholderAPI, PremiumVanish, ProCosmetics, ProtocolLib, ServerListPlus, Shopkeepers, SimpleClans, SimpleRename, SkinsRestorer, Spicord*, TAB, UltimateAutoRestart, UltimateTimber, Vault, VoidGen, VoidSpawn, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by Sidpatchy** [comment]
Continued testing has not reproduced this issue. AWF does not have a message in the entire project matching "Flight enabled". This is an issue with a different plugin.
