### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by xiao0yang** [PyvesB/AntiWorldFly#33]
Plugin Version: 2.5.0

Minecraft Version: 1.12.2

Spigot/CraftBukkit version:  This server is running CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Other Plugins you are using: ![W9Y6~T5K UA2`6AH4JRDCYC](https://user-images.githubusercontent.com/91581933/156930766-fbaa8116-5a2d-4082-a6a1-069eed47433a.png)

## Expected Behavior
fix this bug

## Current Behavior
I used /awf add world to ban the flight of this world, but he didn't work and I could still fly

## Steps to Reproduce

1./awf add world
2.deop <id>
3.start cheat

**Comment by Sidpatchy** [comment]
AntiWorldFly is not an anti-cheat solution. It is designed to block flight gained using methods built into the server such as /fly.
