### ISSUE TITLE
Spectator mode

### ISSUE THREAD

**Issue by christheking** [PyvesB/AntiWorldFly#4]
People in spectator mode will who go to a different world (where flying is disabled) will fall through the world into the void. Possibly make an option to allow flying with spectator mode enabled?

**Comment by PyvesB** [comment]
Hello,

I never use Spectator mode, so I didn't realise that players would fall through the void. I disabled AWF completely in spectator mode, this will be available in the upcoming 2.1.1 release. Please tell me if you have any issues with the update.

EDIT: closing the issue, assuming everything is solved!

Cheers,

Pyves
