### ISSUE TITLE
elytra plugin

### ISSUE THREAD

**Issue by RapisSneeze** [PyvesB/AntiWorldFly#43]
which elytra fly plugin is to used for the plugin

**Comment by Sidpatchy** [comment]
This doesn't make use of an Elytra fly plugin. It simply checks if the server has set the player to be flying, and if it's at a disallowed place disables flight.

The Elytra blocking feature only blocks vanilla Elytra movements, though I suspect plugins allowing for flight with an Elytra would probably be caught up by the flight-blocking functionality -- hard to say without testing specific plugins.

If AWF doesn't work with as expected with an Elytra fly plugin, let me know and I'll look into it!

**Comment by RapisSneeze** [comment]
Is there any plugin which gives elytra to ranked players on join (no rockets)
