### ISSUE TITLE
Misused Command 1.10.2

### ISSUE THREAD

**Issue by ghost** [PyvesB/AntiWorldFly#5]
Hi developer,

I'm constantly getting the "Misused Command" error in 1.10.2 both in game and in console, console output:

```
>awf reload
[16:29:59 INFO]: [۞] Misused command. Please type /awf.
```

There are no other error messages however being thrown out.

Regards

**Comment by PyvesB** [comment]
Hello,

Indeed, the reload and disabled commands were apparently messed up in the latest update. This should be fixed in the upcoming 2.1.1 update.

Thank you for the bug report!

Cheers,

Pyves

**Comment by ghost** [comment]
Thank you for the swift response, It's great to see a pro-active developer! - I look forward to the update.

Regards

**Comment by ghost** [comment]
Working great now, I like how the configs are backed up also, why don't you just code every single minecraft plugin? haha.

Thank's for your time

**Comment by PyvesB** [comment]
No problem, happy to have been able to help!

Unfortunately, I wouldn't have enough time to code every single Minecraft plugin! :-)

Cheers,

Pyves
